//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travelogue_2.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travelogue_2.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir entrada.
        /// </summary>
        internal static string AddEntry {
            get {
                return ResourceManager.GetString("AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir evento.
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir al viaje.
        /// </summary>
        internal static string AddToJourney {
            get {
                return ResourceManager.GetString("AddToJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de viaje vacio.
        /// </summary>
        internal static string AlertNoNameInJourney {
            get {
                return ResourceManager.GetString("AlertNoNameInJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetera.
        /// </summary>
        internal static string CardHolder {
            get {
                return ResourceManager.GetString("CardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Journals completados.
        /// </summary>
        internal static string ClosedEditing {
            get {
                return ResourceManager.GetString("ClosedEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin viajes terminados de editar.
        /// </summary>
        internal static string ClosedEditingEmpty {
            get {
                return ResourceManager.GetString("ClosedEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún viaje cerrado.
        /// </summary>
        internal static string ClosedEmpty {
            get {
                return ResourceManager.GetString("ClosedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viajes cerrados.
        /// </summary>
        internal static string ClosedJourneys {
            get {
                return ResourceManager.GetString("ClosedJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar editando....
        /// </summary>
        internal static string ContinueEditing {
            get {
                return ResourceManager.GetString("ContinueEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin viajes para continuar editando.
        /// </summary>
        internal static string ContinueEditingEmpty {
            get {
                return ResourceManager.GetString("ContinueEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún viaje creado.
        /// </summary>
        internal static string CreatedEmpty {
            get {
                return ResourceManager.GetString("CreatedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viajes creados.
        /// </summary>
        internal static string CreatedJourneys {
            get {
                return ResourceManager.GetString("CreatedJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear una entrada.
        /// </summary>
        internal static string CreateEntry {
            get {
                return ResourceManager.GetString("CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear un evento.
        /// </summary>
        internal static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisa.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MM-yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinos.
        /// </summary>
        internal static string Destinies {
            get {
                return ResourceManager.GetString("Destinies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        internal static string Destiny {
            get {
                return ResourceManager.GetString("Destiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embajadas españolas.
        /// </summary>
        internal static string Embassies {
            get {
                return ResourceManager.GetString("Embassies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce un destino.
        /// </summary>
        internal static string EnterADestiny {
            get {
                return ResourceManager.GetString("EnterADestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas.
        /// </summary>
        internal static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biblioteca.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string LocalizationFirstDay {
            get {
                return ResourceManager.GetString("LocalizationFirstDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres eliminar el viaje? (Las entradas y eventos se eliminarán).
        /// </summary>
        internal static string MessDeleteJourney {
            get {
                return ResourceManager.GetString("MessDeleteJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El destino seleccionado ya está incluido en el viaje.
        /// </summary>
        internal static string MessDestinyAlreadySelected {
            get {
                return ResourceManager.GetString("MessDestinyAlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El viaje se ha creado correctamente.
        /// </summary>
        internal static string MessJourCreated {
            get {
                return ResourceManager.GetString("MessJourCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cambiado el idioma de la aplicación..
        /// </summary>
        internal static string MessLanguageChanged {
            get {
                return ResourceManager.GetString("MessLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe introducir un nombre de viaje.
        /// </summary>
        internal static string MessNoNameInJourney {
            get {
                return ResourceManager.GetString("MessNoNameInJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El viaje ya contiene demasiados destinos..
        /// </summary>
        internal static string MessTooManyDestinies {
            get {
                return ResourceManager.GetString("MessTooManyDestinies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelado.
        /// </summary>
        internal static string Modelation {
            get {
                return ResourceManager.GetString("Modelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEB..
        /// </summary>
        internal static string MonthShort_2 {
            get {
                return ResourceManager.GetString("MonthShort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin resultados.
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar foto.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar un destino....
        /// </summary>
        internal static string SearchDestiny {
            get {
                return ResourceManager.GetString("SearchDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar un viaje....
        /// </summary>
        internal static string SearchJourney {
            get {
                return ResourceManager.GetString("SearchJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar un idioma....
        /// </summary>
        internal static string SearchLanguage {
            get {
                return ResourceManager.GetString("SearchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzar a editar....
        /// </summary>
        internal static string StartEditing {
            get {
                return ResourceManager.GetString("StartEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin viajes para editar.
        /// </summary>
        internal static string StartEditingEmpty {
            get {
                return ResourceManager.GetString("StartEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilo.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacar foto.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
