//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travelogue_2.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travelogue_2.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir entrada.
        /// </summary>
        internal static string AddEntry {
            get {
                return ResourceManager.GetString("AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir evento.
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir reserva.
        /// </summary>
        internal static string AddReservation {
            get {
                return ResourceManager.GetString("AddReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir al viaje.
        /// </summary>
        internal static string AddToJourney {
            get {
                return ResourceManager.GetString("AddToJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo vacio.
        /// </summary>
        internal static string AlertEmptyData {
            get {
                return ResourceManager.GetString("AlertEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin fecha seleccionada.
        /// </summary>
        internal static string AlertNoDaySelected {
            get {
                return ResourceManager.GetString("AlertNoDaySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin imagen seleccionada.
        /// </summary>
        internal static string AlertNoImageSelected {
            get {
                return ResourceManager.GetString("AlertNoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de viaje vacio.
        /// </summary>
        internal static string AlertNoNameInJourney {
            get {
                return ResourceManager.GetString("AlertNoNameInJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin texto.
        /// </summary>
        internal static string AlertNoText {
            get {
                return ResourceManager.GetString("AlertNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada sin título.
        /// </summary>
        internal static string AlertNoTitleInEntry {
            get {
                return ResourceManager.GetString("AlertNoTitleInEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento sin título.
        /// </summary>
        internal static string AlertNoTitleInEvent {
            get {
                return ResourceManager.GetString("AlertNoTitleInEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva sin titulo.
        /// </summary>
        internal static string AlertNoTitleInReservation {
            get {
                return ResourceManager.GetString("AlertNoTitleInReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendario.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie de foto.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetera.
        /// </summary>
        internal static string CardHolder {
            get {
                return ResourceManager.GetString("CardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Journals completados.
        /// </summary>
        internal static string ClosedEditing {
            get {
                return ResourceManager.GetString("ClosedEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin viajes terminados de editar.
        /// </summary>
        internal static string ClosedEditingEmpty {
            get {
                return ResourceManager.GetString("ClosedEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún viaje cerrado.
        /// </summary>
        internal static string ClosedEmpty {
            get {
                return ResourceManager.GetString("ClosedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viajes cerrados.
        /// </summary>
        internal static string ClosedJourneys {
            get {
                return ResourceManager.GetString("ClosedJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar editando....
        /// </summary>
        internal static string ContinueEditing {
            get {
                return ResourceManager.GetString("ContinueEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin viajes para continuar editando.
        /// </summary>
        internal static string ContinueEditingEmpty {
            get {
                return ResourceManager.GetString("ContinueEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún viaje creado.
        /// </summary>
        internal static string CreatedEmpty {
            get {
                return ResourceManager.GetString("CreatedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viajes creados.
        /// </summary>
        internal static string CreatedJourneys {
            get {
                return ResourceManager.GetString("CreatedJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear una entrada.
        /// </summary>
        internal static string CreateEntry {
            get {
                return ResourceManager.GetString("CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear un evento.
        /// </summary>
        internal static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisa.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MM-yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar viaje.
        /// </summary>
        internal static string DeleteJourney {
            get {
                return ResourceManager.GetString("DeleteJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinos.
        /// </summary>
        internal static string Destinies {
            get {
                return ResourceManager.GetString("Destinies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        internal static string Destiny {
            get {
                return ResourceManager.GetString("Destiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embajadas españolas.
        /// </summary>
        internal static string Embassies {
            get {
                return ResourceManager.GetString("Embassies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha fin.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce un destino.
        /// </summary>
        internal static string EnterADestiny {
            get {
                return ResourceManager.GetString("EnterADestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entradas.
        /// </summary>
        internal static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin entradas.
        /// </summary>
        internal static string EntriesEmpty {
            get {
                return ResourceManager.GetString("EntriesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin eventos.
        /// </summary>
        internal static string EventsEmpty {
            get {
                return ResourceManager.GetString("EventsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inicio.
        /// </summary>
        internal static string IniDate {
            get {
                return ResourceManager.GetString("IniDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portada.
        /// </summary>
        internal static string JourneyCover {
            get {
                return ResourceManager.GetString("JourneyCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del viaje.
        /// </summary>
        internal static string JourneyName {
            get {
                return ResourceManager.GetString("JourneyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biblioteca.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string LocalizationFirstDay {
            get {
                return ResourceManager.GetString("LocalizationFirstDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizacion.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los eventos, reservas y entradas asociadas al viaje se eliminaran. Las imagenes seguirán siendo accesibles desde la pestaña &quot;Media&quot;..
        /// </summary>
        internal static string MessButtonDeleteJourney {
            get {
                return ResourceManager.GetString("MessButtonDeleteJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres eliminar el viaje? (Las entradas y eventos se eliminarán).
        /// </summary>
        internal static string MessDeleteJourney {
            get {
                return ResourceManager.GetString("MessDeleteJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El destino seleccionado ya está incluido en el viaje.
        /// </summary>
        internal static string MessDestinyAlreadySelected {
            get {
                return ResourceManager.GetString("MessDestinyAlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe rellenar los campos obligatorios.
        /// </summary>
        internal static string MessEmptyData {
            get {
                return ResourceManager.GetString("MessEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La entrada se ha creado correctamente.
        /// </summary>
        internal static string MessEntryCreated {
            get {
                return ResourceManager.GetString("MessEntryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El evento se ha creado correctamente.
        /// </summary>
        internal static string MessEventCreated {
            get {
                return ResourceManager.GetString("MessEventCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen se ha añadido correctamente.
        /// </summary>
        internal static string MessImageAdded {
            get {
                return ResourceManager.GetString("MessImageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La información se ha añadido correctamente.
        /// </summary>
        internal static string MessInfoAdded {
            get {
                return ResourceManager.GetString("MessInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si cierra la pestaña la información introducida se perderá.
        /// </summary>
        internal static string MessInfoWillBeLost {
            get {
                return ResourceManager.GetString("MessInfoWillBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El viaje se ha creado correctamente.
        /// </summary>
        internal static string MessJourCreated {
            get {
                return ResourceManager.GetString("MessJourCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cambiado el idioma de la aplicación.
        /// </summary>
        internal static string MessLanguageChanged {
            get {
                return ResourceManager.GetString("MessLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe seleccionar una fecha.
        /// </summary>
        internal static string MessNoDaySelected {
            get {
                return ResourceManager.GetString("MessNoDaySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe seleccionar una imagen.
        /// </summary>
        internal static string MessNoImageSelected {
            get {
                return ResourceManager.GetString("MessNoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe introducir un nombre de viaje.
        /// </summary>
        internal static string MessNoNameInJourney {
            get {
                return ResourceManager.GetString("MessNoNameInJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe introducir un texto.
        /// </summary>
        internal static string MessNoText {
            get {
                return ResourceManager.GetString("MessNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe introducir un título a la entrada.
        /// </summary>
        internal static string MessNoTitleInEntry {
            get {
                return ResourceManager.GetString("MessNoTitleInEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe introducir un título al evento.
        /// </summary>
        internal static string MessNoTitleInEvent {
            get {
                return ResourceManager.GetString("MessNoTitleInEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se debe introducir un título a la reserva.
        /// </summary>
        internal static string MessNoTitleInReservation {
            get {
                return ResourceManager.GetString("MessNoTitleInReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La reserva se ha creado correctamente.
        /// </summary>
        internal static string MessReservationCreated {
            get {
                return ResourceManager.GetString("MessReservationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El texto se ha añadido correctamente.
        /// </summary>
        internal static string MessTextAdded {
            get {
                return ResourceManager.GetString("MessTextAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El viaje ya contiene demasiados destinos.
        /// </summary>
        internal static string MessTooManyDestinies {
            get {
                return ResourceManager.GetString("MessTooManyDestinies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelado.
        /// </summary>
        internal static string Modelation {
            get {
                return ResourceManager.GetString("Modelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEB..
        /// </summary>
        internal static string MonthShort_2 {
            get {
                return ResourceManager.GetString("MonthShort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin resultados.
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de tfn..
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar foto.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva.
        /// </summary>
        internal static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar un destino....
        /// </summary>
        internal static string SearchDestiny {
            get {
                return ResourceManager.GetString("SearchDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar un viaje....
        /// </summary>
        internal static string SearchJourney {
            get {
                return ResourceManager.GetString("SearchJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar un idioma....
        /// </summary>
        internal static string SearchLanguage {
            get {
                return ResourceManager.GetString("SearchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzar a editar....
        /// </summary>
        internal static string StartEditing {
            get {
                return ResourceManager.GetString("StartEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin viajes para editar.
        /// </summary>
        internal static string StartEditingEmpty {
            get {
                return ResourceManager.GetString("StartEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilo.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilos.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacar foto.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
