//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travelogue_2.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Travelogue_2.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir tarjeta.
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DNI, NIF, pasaporte....
        /// </summary>
        internal static string AddCardEx {
            get {
                return ResourceManager.GetString("AddCardEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir destino.
        /// </summary>
        internal static string AddDestiny {
            get {
                return ResourceManager.GetString("AddDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir entrada.
        /// </summary>
        internal static string AddEntry {
            get {
                return ResourceManager.GetString("AddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir evento.
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir reserva.
        /// </summary>
        internal static string AddReservation {
            get {
                return ResourceManager.GetString("AddReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir al viaje.
        /// </summary>
        internal static string AddToJourney {
            get {
                return ResourceManager.GetString("AddToJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo vacio.
        /// </summary>
        internal static string AlertEmptyData {
            get {
                return ResourceManager.GetString("AlertEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin fecha seleccionada.
        /// </summary>
        internal static string AlertNoDaySelected {
            get {
                return ResourceManager.GetString("AlertNoDaySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin imagen seleccionada.
        /// </summary>
        internal static string AlertNoImageSelected {
            get {
                return ResourceManager.GetString("AlertNoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta sin imagenes.
        /// </summary>
        internal static string AlertNoImagesInCard {
            get {
                return ResourceManager.GetString("AlertNoImagesInCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta sin nombre.
        /// </summary>
        internal static string AlertNoNameInCard {
            get {
                return ResourceManager.GetString("AlertNoNameInCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viaje sin nombre.
        /// </summary>
        internal static string AlertNoNameInJourney {
            get {
                return ResourceManager.GetString("AlertNoNameInJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin texto.
        /// </summary>
        internal static string AlertNoText {
            get {
                return ResourceManager.GetString("AlertNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada sin título.
        /// </summary>
        internal static string AlertNoTitleInEntry {
            get {
                return ResourceManager.GetString("AlertNoTitleInEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento sin título.
        /// </summary>
        internal static string AlertNoTitleInEvent {
            get {
                return ResourceManager.GetString("AlertNoTitleInEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva sin titulo.
        /// </summary>
        internal static string AlertNoTitleInReservation {
            get {
                return ResourceManager.GetString("AlertNoTitleInReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Travelogue.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reverso.
        /// </summary>
        internal static string BackImage {
            get {
                return ResourceManager.GetString("BackImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario.
        /// </summary>
        internal static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pie de foto.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjetera.
        /// </summary>
        internal static string CardHolder {
            get {
                return ResourceManager.GetString("CardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Journals completados.
        /// </summary>
        internal static string ClosedEditing {
            get {
                return ResourceManager.GetString("ClosedEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin viajes terminados de editar.
        /// </summary>
        internal static string ClosedEditingEmpty {
            get {
                return ResourceManager.GetString("ClosedEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún viaje cerrado.
        /// </summary>
        internal static string ClosedEmpty {
            get {
                return ResourceManager.GetString("ClosedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes cerrados.
        /// </summary>
        internal static string ClosedJourneys {
            get {
                return ResourceManager.GetString("ClosedJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viaje cerrado.
        /// </summary>
        internal static string ClosedMessage {
            get {
                return ResourceManager.GetString("ClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar editando....
        /// </summary>
        internal static string ContinueEditing {
            get {
                return ResourceManager.GetString("ContinueEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin viajes para continuar editando.
        /// </summary>
        internal static string ContinueEditingEmpty {
            get {
                return ResourceManager.GetString("ContinueEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún viaje creado.
        /// </summary>
        internal static string CreatedEmpty {
            get {
                return ResourceManager.GetString("CreatedEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viaje sin abrir.
        /// </summary>
        internal static string CreatedJourneyMessage {
            get {
                return ResourceManager.GetString("CreatedJourneyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajes creados.
        /// </summary>
        internal static string CreatedJourneys {
            get {
                return ResourceManager.GetString("CreatedJourneys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una entrada.
        /// </summary>
        internal static string CreateEntry {
            get {
                return ResourceManager.GetString("CreateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear un evento.
        /// </summary>
        internal static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisa.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd-MM-yyyy.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar viaje.
        /// </summary>
        internal static string DeleteJourney {
            get {
                return ResourceManager.GetString("DeleteJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destinos.
        /// </summary>
        internal static string Destinies {
            get {
                return ResourceManager.GetString("Destinies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino.
        /// </summary>
        internal static string Destiny {
            get {
                return ResourceManager.GetString("Destiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Embajadas españolas.
        /// </summary>
        internal static string Embassies {
            get {
                return ResourceManager.GetString("Embassies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha fin.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar diario de viaje.
        /// </summary>
        internal static string EndJournal {
            get {
                return ResourceManager.GetString("EndJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce un destino.
        /// </summary>
        internal static string EnterADestiny {
            get {
                return ResourceManager.GetString("EnterADestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entradas.
        /// </summary>
        internal static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin entradas.
        /// </summary>
        internal static string EntriesEmpty {
            get {
                return ResourceManager.GetString("EntriesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin eventos.
        /// </summary>
        internal static string EventsEmpty {
            get {
                return ResourceManager.GetString("EventsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Galería.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagenes.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguna imagen para mostrar.
        /// </summary>
        internal static string ImagesEmpty {
            get {
                return ResourceManager.GetString("ImagesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inicio.
        /// </summary>
        internal static string IniDate {
            get {
                return ResourceManager.GetString("IniDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portada.
        /// </summary>
        internal static string JourneyCover {
            get {
                return ResourceManager.GetString("JourneyCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del viaje.
        /// </summary>
        internal static string JourneyName {
            get {
                return ResourceManager.GetString("JourneyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viaje sin imagenes.
        /// </summary>
        internal static string JourneyWithoutImages {
            get {
                return ResourceManager.GetString("JourneyWithoutImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string LocalizationFirstDay {
            get {
                return ResourceManager.GetString("LocalizationFirstDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los eventos, reservas y entradas asociadas al viaje se eliminaran. Las imagenes seguirán siendo accesibles desde la pestaña &quot;Media&quot;..
        /// </summary>
        internal static string MessButtonDeleteJourney {
            get {
                return ResourceManager.GetString("MessButtonDeleteJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarjeta se ha creado correctamente.
        /// </summary>
        internal static string MessCardCreated {
            get {
                return ResourceManager.GetString("MessCardCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos de los días ya pertenecen a otros viajes.
        /// </summary>
        internal static string MessDatesAlreadyInUse {
            get {
                return ResourceManager.GetString("MessDatesAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a eliminar un día con informacion ¿Continuar?.
        /// </summary>
        internal static string MessDayInfoWillBeLost {
            get {
                return ResourceManager.GetString("MessDayInfoWillBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres eliminar el viaje? (Las entradas y eventos se eliminarán).
        /// </summary>
        internal static string MessDeleteJourney {
            get {
                return ResourceManager.GetString("MessDeleteJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El destino seleccionado ya está incluido en el viaje.
        /// </summary>
        internal static string MessDestinyAlreadySelected {
            get {
                return ResourceManager.GetString("MessDestinyAlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe rellenar los campos obligatorios.
        /// </summary>
        internal static string MessEmptyData {
            get {
                return ResourceManager.GetString("MessEmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarjeta se ha eliminado.
        /// </summary>
        internal static string MessEntryCardDeleted {
            get {
                return ResourceManager.GetString("MessEntryCardDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entrada se ha creado correctamente.
        /// </summary>
        internal static string MessEntryCreated {
            get {
                return ResourceManager.GetString("MessEntryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información se ha eliminado de la entrada.
        /// </summary>
        internal static string MessEntryDataDeleted {
            get {
                return ResourceManager.GetString("MessEntryDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entrada se ha eliminado.
        /// </summary>
        internal static string MessEntryDeleted {
            get {
                return ResourceManager.GetString("MessEntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entrada se ha guardado correctamente.
        /// </summary>
        internal static string MessEntrySaved {
            get {
                return ResourceManager.GetString("MessEntrySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El evento se ha creado correctamente.
        /// </summary>
        internal static string MessEventCreated {
            get {
                return ResourceManager.GetString("MessEventCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El evento se ha eliminado.
        /// </summary>
        internal static string MessEventDeleted {
            get {
                return ResourceManager.GetString("MessEventDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El evento se ha guardado correctamente.
        /// </summary>
        internal static string MessEventSaved {
            get {
                return ResourceManager.GetString("MessEventSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen se ha añadido correctamente.
        /// </summary>
        internal static string MessImageAdded {
            get {
                return ResourceManager.GetString("MessImageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen se ha guardado correctamente.
        /// </summary>
        internal static string MessImageSaved {
            get {
                return ResourceManager.GetString("MessImageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a eliminar la imagen ¿Continuar?.
        /// </summary>
        internal static string MessImageWillBeDeleted {
            get {
                return ResourceManager.GetString("MessImageWillBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información se ha añadido correctamente.
        /// </summary>
        internal static string MessInfoAdded {
            get {
                return ResourceManager.GetString("MessInfoAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si cierra la pestaña la información introducida se perderá.
        /// </summary>
        internal static string MessInfoWillBeLost {
            get {
                return ResourceManager.GetString("MessInfoWillBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El viaje se ha creado correctamente.
        /// </summary>
        internal static string MessJourCreated {
            get {
                return ResourceManager.GetString("MessJourCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha eliminado el viaje correctamente.
        /// </summary>
        internal static string MessJourneyDeleted {
            get {
                return ResourceManager.GetString("MessJourneyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un viaje registrado con ese nombre.
        /// </summary>
        internal static string MessJourneyNameAlreadUsed {
            get {
                return ResourceManager.GetString("MessJourneyNameAlreadUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cambiado el idioma de la aplicación.
        /// </summary>
        internal static string MessLanguageChanged {
            get {
                return ResourceManager.GetString("MessLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las fechas de un viaje cerrado no se pueden modificar.
        /// </summary>
        internal static string MessModifyDatesInClosedJourney {
            get {
                return ResourceManager.GetString("MessModifyDatesInClosedJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha inicial de un viaje abierto no se puede modificar.
        /// </summary>
        internal static string MessModifyIniDateInOpenJourney {
            get {
                return ResourceManager.GetString("MessModifyIniDateInOpenJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe seleccionar una fecha.
        /// </summary>
        internal static string MessNoDaySelected {
            get {
                return ResourceManager.GetString("MessNoDaySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe seleccionar una imagen.
        /// </summary>
        internal static string MessNoImageSelected {
            get {
                return ResourceManager.GetString("MessNoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se deben introducir las dos imagenes en la tarjeta.
        /// </summary>
        internal static string MessNoImagesInCard {
            get {
                return ResourceManager.GetString("MessNoImagesInCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe introducir un nombre a la tarjeta.
        /// </summary>
        internal static string MessNoNameInCard {
            get {
                return ResourceManager.GetString("MessNoNameInCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe introducir un nombre de viaje.
        /// </summary>
        internal static string MessNoNameInJourney {
            get {
                return ResourceManager.GetString("MessNoNameInJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe introducir un texto.
        /// </summary>
        internal static string MessNoText {
            get {
                return ResourceManager.GetString("MessNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe introducir un título a la entrada.
        /// </summary>
        internal static string MessNoTitleInEntry {
            get {
                return ResourceManager.GetString("MessNoTitleInEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe introducir un título al evento.
        /// </summary>
        internal static string MessNoTitleInEvent {
            get {
                return ResourceManager.GetString("MessNoTitleInEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe introducir un título a la reserva.
        /// </summary>
        internal static string MessNoTitleInReservation {
            get {
                return ResourceManager.GetString("MessNoTitleInReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La reserva se ha creado correctamente.
        /// </summary>
        internal static string MessReservationCreated {
            get {
                return ResourceManager.GetString("MessReservationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El texto se ha añadido correctamente.
        /// </summary>
        internal static string MessTextAdded {
            get {
                return ResourceManager.GetString("MessTextAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El viaje ya contiene demasiados destinos.
        /// </summary>
        internal static string MessTooManyDestinies {
            get {
                return ResourceManager.GetString("MessTooManyDestinies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alguno de los días seleccionados tiene el maximo de eventos permitidos.
        /// </summary>
        internal static string MessTooManyEvents {
            get {
                return ResourceManager.GetString("MessTooManyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -.
        /// </summary>
        internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelado.
        /// </summary>
        internal static string Modelation {
            get {
                return ResourceManager.GetString("Modelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENE..
        /// </summary>
        internal static string MonthShort_1 {
            get {
                return ResourceManager.GetString("MonthShort_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCT..
        /// </summary>
        internal static string MonthShort_10 {
            get {
                return ResourceManager.GetString("MonthShort_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOV..
        /// </summary>
        internal static string MonthShort_11 {
            get {
                return ResourceManager.GetString("MonthShort_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIC..
        /// </summary>
        internal static string MonthShort_12 {
            get {
                return ResourceManager.GetString("MonthShort_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FEB..
        /// </summary>
        internal static string MonthShort_2 {
            get {
                return ResourceManager.GetString("MonthShort_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAR..
        /// </summary>
        internal static string MonthShort_3 {
            get {
                return ResourceManager.GetString("MonthShort_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABR..
        /// </summary>
        internal static string MonthShort_4 {
            get {
                return ResourceManager.GetString("MonthShort_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAY..
        /// </summary>
        internal static string MonthShort_5 {
            get {
                return ResourceManager.GetString("MonthShort_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUN..
        /// </summary>
        internal static string MonthShort_6 {
            get {
                return ResourceManager.GetString("MonthShort_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUL..
        /// </summary>
        internal static string MonthShort_7 {
            get {
                return ResourceManager.GetString("MonthShort_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AGO..
        /// </summary>
        internal static string MonthShort_8 {
            get {
                return ResourceManager.GetString("MonthShort_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEP..
        /// </summary>
        internal static string MonthShort_9 {
            get {
                return ResourceManager.GetString("MonthShort_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin pie de foto.
        /// </summary>
        internal static string NoCaption {
            get {
                return ResourceManager.GetString("NoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin viaje asociado.
        /// </summary>
        internal static string NoJourneyAssociated {
            get {
                return ResourceManager.GetString("NoJourneyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin resultados.
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} páginas.
        /// </summary>
        internal static string PagesCountMess {
            get {
                return ResourceManager.GetString("PagesCountMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de tfn..
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotos.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar foto.
        /// </summary>
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rehacer.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva.
        /// </summary>
        internal static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicializar.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar un destino....
        /// </summary>
        internal static string SearchDestiny {
            get {
                return ResourceManager.GetString("SearchDestiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar un viaje....
        /// </summary>
        internal static string SearchJourney {
            get {
                return ResourceManager.GetString("SearchJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar un idioma....
        /// </summary>
        internal static string SearchLanguage {
            get {
                return ResourceManager.GetString("SearchLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un fondo.
        /// </summary>
        internal static string SelectABackground {
            get {
                return ResourceManager.GetString("SelectABackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzar a editar....
        /// </summary>
        internal static string StartEditing {
            get {
                return ResourceManager.GetString("StartEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin viajes para editar.
        /// </summary>
        internal static string StartEditingEmpty {
            get {
                return ResourceManager.GetString("StartEditingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilo.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estilos.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sacar foto.
        /// </summary>
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cara.
        /// </summary>
        internal static string TopImage {
            get {
                return ResourceManager.GetString("TopImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deshacer.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
